model:
    _target_: segmentation_models_pytorch.UnetPlusPlus
    encoder_name: timm-efficientnet-l2
    encoder_weights: noisy-student
    classes: 29

optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001
    weight_decay: 0.000001

scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    T_max : 100
    eta_min: 0.000001